"""Add amount field to Product

Revision ID: 60077ed51569
Revises: 62f9e531c4f9
Create Date: 2025-07-22 20:11:50.710814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60077ed51569'
down_revision = '62f9e531c4f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
