"""Add category to Product

Revision ID: 62f9e531c4f9
Revises: a0b247311c6b
Create Date: 2025-07-17 21:34:39.979686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62f9e531c4f9'
down_revision = 'a0b247311c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('min_order_qty')
        batch_op.drop_column('price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('min_order_qty', mysql.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
